version: 2

models:
  - name: fct_deliveries
    description: "Final fact table for delivery performance analysis."
    columns:
      - name: order_id
        data_tests:
          - unique
          - not_null
      - name: user_id
        data_tests:
          - not_null
      - name: is_severely_delayed
        data_tests:
          - not_null
          - accepted_values:
              values: [true, false]
      - name: zone
        description: "Geographic delivery zone."
        data_tests:
          - not_null
      - name: category
        description: "Order category (e.g., Food, Pharmacy)."
        data_tests:
          - not_null
